### ISSUE TITLE
Parse Error in names.wast spec

### ISSUE THREAD

**Issue by bjfish** [pepyakin/wabt-rs#50]
I am getting a parse error for parts of the `names.wast` from the WebAssembly spec suite:
https://github.com/WebAssembly/spec/blob/master/test/core/names.wast

Error
```
$ RUST_BACKTRACE=1 cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.02s
     Running `target/debug/wabt_parse`
in Module
in AssertReturn
in AssertReturn
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: FromUtf8Error { bytes: [255], error: Utf8Error { valid_up_to: 0, error_len: Some(1) } }', src/libcore/result.rs:999:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: std::panicking::try::do_call
             at src/libstd/panicking.rs:308
   7: <T as core::any::Any>::type_id
             at src/libcore/panicking.rs:85
   8: hashbrown::raw::bitmask::BitMask::invert
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libcore/macros.rs:18
   9: hashbrown::raw::bitmask::BitMask::invert
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libcore/result.rs:800
  10: core::ptr::swap_nonoverlapping_bytes
             at /Users/brandonfish/.cargo/registry/src/github.com-1ecc6299db9ec823/wabt-0.9.0/src/script/mod.rs:267
  11: wabt::script::parse_action
             at /Users/brandonfish/.cargo/registry/src/github.com-1ecc6299db9ec823/wabt-0.9.0/src/script/mod.rs:280
  12: wabt::script::ScriptParser<F32,F64>::next
             at /Users/brandonfish/.cargo/registry/src/github.com-1ecc6299db9ec823/wabt-0.9.0/src/script/mod.rs:530
  13: wabt_parse::main
             at src/main.rs:30
  14: std::rt::lang_start::{{closure}}
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/rt.rs:64
  15: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
  16: panic_unwind::dwarf::eh::read_encoded_pointer
             at src/libpanic_unwind/lib.rs:85
  17: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at src/libstd/panicking.rs:272
             at src/libstd/panic.rs:394
             at src/libstd/rt.rs:48
  18: std::rt::lang_start
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/rt.rs:64
  19: wabt_parse::main
```

Example:
Around lines: https://github.com/WebAssembly/spec/blob/a221f2574d7106e92cf8abaf05d5bb1131b19d76/test/core/names.wast#L58
```
use wabt::script::{Action, Command, CommandKind, Error, ScriptParser, Value};

fn main() -> Result<(), wabt::script::Error> {
    let wast = r#"
(module 
  ;; Test that names are case-sensitive.
  (func (export "a") (result i32) (i32.const 13))
  (func (export "A") (result i32) (i32.const 14))

  ;; Test that UTF-8 BOM code points can appear in identifiers.
  (func (export "﻿") (result i32) (i32.const 15))

  ;; Test that Unicode normalization is not applied. These function names
  ;; contain different codepoints which normalize to the same thing under
  ;; NFC or NFD.
  (func (export "Å") (result i32) (i32.const 16))
  (func (export "Å") (result i32) (i32.const 17))
  (func (export "Å") (result i32) (i32.const 18))
)
 
(assert_return (invoke "a") (i32.const 13))
(assert_return (invoke "A") (i32.const 14))
(assert_return (invoke "﻿") (i32.const 15))
(assert_return (invoke "Å") (i32.const 16))
(assert_return (invoke "Å") (i32.const 17))
(assert_return (invoke "Å") (i32.const 18))
"#;

    let mut parser: ScriptParser = ScriptParser::from_str(wast)?;
    while let Some(Command { kind, .. }) = parser.next()? {
        match kind {
            CommandKind::Module { module, name } => {
                println!("in Module");
            }
            CommandKind::AssertReturn { action, expected } => {
                println!("in AssertReturn");
            }
            _ => panic!("there are no other commands apart from that defined above"),
        }
    }
    Ok(())
}
```

**Comment by yurydelendik** [comment]
The same issue here. Looks like https://github.com/WebAssembly/wabt/commit/d1bb5f81541e670b8d088f158d08c99a6a973281 (found via bisect) doing all job now and `jstring_to_rstring` at https://github.com/pepyakin/wabt-rs/blob/master/src/script/mod.rs#L261 is not needed.

**Comment by pepyakin** [comment]
Thanks for the report. I'd be able to fix the issue only starting from Monday.

**Comment by yurydelendik** [comment]
Is it possible to make (minor?) version bump for this fix? Thanks

**Comment by pepyakin** [comment]
Sure! 0.9.1 is out.
